name: CI
on: [push, pull_request]
jobs:
  build:
    name: Test in Ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Run the tests
        run: |
          docker-compose up --exit-code-from medusa-client
