name: CI
on: [push, pull_request]
jobs:
  build:
    name: Test in Ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@master
        with:
          aws-region: us-east-2
          role-to-assume: arn:aws:iam::721945215539:role/github-actions-medusa-client
          role-session-name: GithubActionsSession
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Run the tests
        run: |
          docker-compose up --exit-code-from medusa-client
